on Long Press: Edit, Delete and Duplicate
a-mabe/OpenHIIT pull request #133
Opened 2024-01-21 12:37 UTC by Krunal-375

# Fixes issue #129 

Hey @a-mabe I have added long press functionality which allow user to edit, delete and duplicate workout kindly review it.
## Here is demo video:

https://github.com/a-mabe/OpenHIIT/assets/72144846/d779cc0e-03ae-442e-b003-508817280755

2024-01-21 18:36 UTC, a-mabe requested changes
Thank you for the contribution @Krunal-375!

The duplicate workout functionality works great, and the video of the functionality is appreciated.

I have provided feedback on the use of onLongPress as well as an alternative. I had a couple of testers find it difficult to continue using the drag and drop workout reorder feature due to the conflicting gestures. However I do like the idea of the onLongPress menu, I am not sure how to better adjust the sensitivity of the onLongPress and onDrag gestures.

2024-01-22 01:09 UTC, Krunal-375 commented on lib/duplicate_feature/duplicate_workout.dart
> +import 'package:openhiit/workout_data_type/workout_type.dart';
I have removed the duplicate_feature folder

2024-01-22 02:24 UTC, Krunal-375 commented on lib/main.dart
> +            onLongPress: (){
I have made the following changes

2024-01-22 12:42 UTC, a-mabe requested changes
Thank you for making those changes @Krunal-375. I found an old comment that needed fixed, but otherwise this is working great, thank you!

2024-01-22 12:42 UTC, a-mabe commented on lib/main.dart
> +          /// This is a GestureDetector widget that is used to handle different types of touch events.
Please remove the comment referencing the gesture detector as it is no longer being used

2024-01-22 12:42 UTC, a-mabe commented on lib/main.dart
> -                '${workout.workoutIndex}'), // Unique key for each list item.
Please add back these comments in `main.dart`

2024-01-22 13:41 UTC, a-mabe approved these changes

2024-01-22 13:41 UTC, merged